### ISSUE TITLE
The mca-website-strategy failure to retrieve access token

### ISSUE THREAD

**Issue by baumblatt** [ibm-bluemix-mobile-services/bms-mca-token-validation-strategy#7]
Hello MCA Team,

I'm developing an application with web client and mobile client using the Mobile Access Control service on IBM Bluemix.

I'm trying to use mca-website-strategy to protect the web client as well the mobile client is protected by mca-backend-strategy. 

But the component was unable to retrieve access token, during the last step of authentication process.

The failure is caused by an mistake on line 90 of the file:
/node_modules/bms-mca-token-validation-strategy/lib/mca-website-strategy.js

Version 2.0.8 code:
line 90: `grant_type: "code",`

The working code:
line 90: `grant_type: "authorization_code",`

I'm looking forward for a working release as soon as possible.

Best regards,
Bernardo Baumblatt.

**Comment by rotembr** [comment]
Hi,
I published a new version (2.0.9) with that fix.
Thank you.

**Comment by baumblatt** [comment]
Hello,

Working like a charm, thank you for the agility.

Regards,
Bernardo
